name: Docker Image CI

# Indica cuando se disparara el trigger para realizar la action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
# Pasos a seguir
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        echo "Iniciando Login"
        echo  $DOCKER_USER
        echo $DOCKER_PASSWORD
        echo "Fin del Login"
#    - name: Build the Docker image
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
